<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Objectives" data-toc-modified-id="Objectives-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Objectives</a></span></li><li><span><a href="#1.-Define-two-arrays-A-(4x2)-and-B-(2x3)" data-toc-modified-id="1.-Define-two-arrays-A-(4x2)-and-B-(2x3)-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>1. Define two arrays A (4x2) and B (2x3)</a></span></li><li><span><a href="#2.-Print-the-dimensions-of-A-and-B" data-toc-modified-id="2.-Print-the-dimensions-of-A-and-B-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>2. Print the dimensions of A and B</a></span></li><li><span><a href="#3.-Print-some-of-the-elements-from-A-at-following-locations" data-toc-modified-id="3.-Print-some-of-the-elements-from-A-at-following-locations-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>3. Print some of the elements from A at following locations</a></span></li><li><span><a href="#4.-Write-a-routine-to-populate-matrix-with-random-data" data-toc-modified-id="4.-Write-a-routine-to-populate-matrix-with-random-data-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>4. Write a routine to populate matrix with random data</a></span></li><li><span><a href="#5.-Turn-above-routine-into-a-function." data-toc-modified-id="5.-Turn-above-routine-into-a-function.-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>5. Turn above routine into a function.</a></span></li><li><span><a href="#Summary" data-toc-modified-id="Summary-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Summary</a></span></li></ul></div>

# Vectors and Matrices in Numpy - Lab

## Introduction

This lab will ask you to perform some simple matrix creation and manipulation exercises based on what we have covered so far in this section. The key takeaway here for you is to be able to understand how to using indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays A (4x2) and B (2x3) 
```
A = 1402, 191 
    1371, 821 
    949, 1437
    147, 1448
    
B = 1, 2, 3
    4, 5, 6
    ```

In [1]:
# Code Here
import numpy as np
A = np.array([[1402, 191],[1371, 821],[949, 1437],[147, 1448]])
B = np.array([[1, 2, 3],[4, 5, 6]])
print(A)
print(B)

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
[[1 2 3]
 [4 5 6]]


## 2. Print the dimensions of A and B 

In [2]:
# Code Here
print(f'Shape of A: {A.shape}')
print(f'Shape of B: {B.shape}')

Shape of A: (4, 2)
Shape of B: (2, 3)


## 3. Print some of the elements from A at following locations
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [3]:
# Code Here
print(A[0,0])
print(A[0,1])
print(A[2,1])
print(A[3,0])

1402
191
1437
147


## 4. Write a routine to populate matrix with random data
* Create an 3x3 numpy array with all zeros (use `np.zeros()`)
* Access each location i,j of this matrix and fill in random values between the range 1 and 10. 

In [26]:
# Code Here (due to random data , your output might be different)
A = np.zeros((3,3))
for i in range(3):
    A[i] = np.random.uniform(1,10,3)
print(len(A))

3


## 5. Turn above routine into a function.
* Create two 4x4 zero valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [31]:
# Code Here (due to random data , your output might be different)
def fill_random(array, min_val, max_val):
    for i in range(len(array)):
        array[i] = np.random.uniform(min_val, max_val, len(array))
    return array

A = np.zeros((4,4))
A = fill_random(A, 1, 10)
B = np.zeros((4,4))
B = fill_random(B, 1, 10)

print(A+B)

[[14.05851342 14.06485789 10.5929967  10.30958518]
 [ 5.03921275  7.99504835 10.09802592  8.63521325]
 [15.8112296  14.13658557 12.21217044 11.2438331 ]
 [11.33602318  9.15242829 15.20296154  9.98065925]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 